genreWords = {
    "nationality": [
        "Afghan",
        "Albanian",
        "Algerian",
        "American",
        "Andorran",
        "Angolan",
        "Antiguans",
        "Argentinean",
        "Armenian",
        "Australian",
        "Austrian",
        "Azerbaijani",
        "Bahamian",
        "Bahraini",
        "Bangladeshi",
        "Barbadian",
        "Barbudans",
        "Batswana",
        "Belarusian",
        "Belgian",
        "Belizean",
        "Beninese",
        "Bhutanese",
        "Bolivian",
        "Bosnian",
        "Brazilian",
        "British",
        "Bruneian",
        "Bulgarian",
        "Burkinabe",
        "Burmese",
        "Burundian",
        "Cambodian",
        "Cameroonian",
        "Canadian",
        "Cape Verdean",
        "Central African",
        "Chadian",
        "Chilean",
        "Chinese",
        "Colombian",
        "Comoran",
        "Congolese",
        "Costa Rican",
        "Croatian",
        "Cuban",
        "Cypriot",
        "Czech",
        "Danish",
        "Djibouti",
        "Dominican",
        "Dutch",
        "East Timorese",
        "Ecuadorean",
        "Egyptian",
        "Emirian",
        "Equatorial Guinean",
        "Eritrean",
        "Estonian",
        "Ethiopian",
        "Fijian",
        "Filipino",
        "Finnish",
        "French",
        "Gabonese",
        "Gambian",
        "Georgian",
        "German",
        "Ghanaian",
        "Greek",
        "Grenadian",
        "Guatemalan",
        "Guinea-Bissauan",
        "Guinean",
        "Guyanese",
        "Haitian",
        "Herzegovinian",
        "Honduran",
        "Hungarian",
        "I-Kiribati",
        "Icelander",
        "Indian",
        "Indonesian",
        "Iranian",
        "Iraqi",
        "Irish",
        "Israeli",
        "Italian",
        "Ivorian",
        "Jamaican",
        "Japanese",
        "Jordanian",
        "Kazakhstani",
        "Kenyan",
        "Kittian and Nevisian",
        "Kuwaiti",
        "Kyrgyz",
        "Laotian",
        "Latvian",
        "Lebanese",
        "Liberian",
        "Libyan",
        "Liechtensteiner",
        "Lithuanian",
        "Luxembourger",
        "Macedonian",
        "Malagasy",
        "Malawian",
        "Malaysian",
        "Maldivan",
        "Malian",
        "Maltese",
        "Marshallese",
        "Mauritanian",
        "Mauritian",
        "Mexican",
        "Micronesian",
        "Moldovan",
        "Monacan",
        "Mongolian",
        "Moroccan",
        "Mosotho",
        "Motswana",
        "Mozambican",
        "Namibian",
        "Nauruan",
        "Nepalese",
        "New Zealander",
        "Nicaraguan",
        "Nigerian",
        "Nigerien",
        "North Korean",
        "Northern Irish",
        "Norwegian",
        "Omani",
        "Pakistani",
        "Palauan",
        "Panamanian",
        "Papua New Guinean",
        "Paraguayan",
        "Peruvian",
        "Polish",
        "Portuguese",
        "Qatari",
        "Romanian",
        "Russian",
        "Rwandan",
        "Saint Lucian",
        "Salvadoran",
        "Samoan",
        "San Marinese",
        "Sao Tomean",
        "Saudi",
        "Scottish",
        "Senegalese",
        "Serbian",
        "Seychellois",
        "Sierra Leonean",
        "Singaporean",
        "Slovakian",
        "Slovenian",
        "Solomon Islander",
        "Somali",
        "South African",
        "South Korean",
        "Spanish",
        "Sri Lankan",
        "Sudanese",
        "Surinamer",
        "Swazi",
        "Swedish",
        "Swiss",
        "Syrian",
        "Taiwanese",
        "Tajik",
        "Tanzanian",
        "Thai",
        "Togolese",
        "Tongan",
        "Trinidadian",
        "Tobagonian",
        "Tunisian",
        "Turkish",
        "Tuvaluan",
        "Ugandan",
        "Ukrainian",
        "Uruguayan",
        "Uzbekistani",
        "Venezuelan",
        "Vietnamese",
        "Welsh",
        "Yemenite",
        "Zambian",
        "Zimbabwean",
        "Chorennian",
        "Xaigonian",
        "Achaian",
        "Oxarean",
        "Qaidellian",
        "Mosian",
        "Gulberg",
        "Tollian",
        "Shrewgamic"
    ],
    "starters": [
        "New Wave",
        "Blackened",
        "Christian",
        "Melodic",
        "Symphonic",
        "Ambient"
    ],
    "fillers": [
        "Technical",
        "Progressive",
        "Avant-Garde",
        "Brutal",
        "Folk",
        "Viking",
        "Pirate",
        "Stoner",
        "Pagan",
        "Power",
        "Groove",
        "Alternative",
        "Funk",
        "Rap",
        "Black",
        "Atmospheric",
        "Depressive",
        "War",
        "Funeral",
        "Traditional",
        "Glam",
        "Gothic",
        "Hard",
        "Rock",
        "Heavy",
        "Psych",
        "Punk",
        "Industrial",
        "Neoclassical",
        "Speed",
        "Trance"
    ],
    "core": [
        "Hardcore",
        "Metalcore",
        "Deathcore",
        "Electronicore",
        "Mathcore",
        "Nintendocore",
        "Grindcore",
    ],
    "grind": [
        "Cybergrind",
        "Goregrind",
        "Pornogrind",
    ],
    "prefix": [
        "Nu",
        "Proto",
        "Crust"
    ],
    "enders": [
        "Death",
        "Thrash",
        "Doom",
        "Sludge",
        "Drone",
        "Crossover"
    ]
}

nationalities = {
    "Chorenn": {
        "noun": "Chorenn",
        "verb": "Chorennian"
    },
    "Xagon": {
        "noun": "Xagon",
        "verb": "Xaigonian"
    },
    "Achaea": {
        "noun": "Achaea",
        "verb": "Achaian"
    }, 
    "Oxares": {
        "noun": "Oxares",
        "verb": "Oxarean"
    },
    "Qaidel": {
        "noun": "Qaidel",
        "verb": "Qaidellian"
    },
    "Mose": {
        "noun": "Mose",
        "verb": "Mosian"
    },
    "Gulbering": {
        "noun": "Gulbering",
        "verb": "Gulberg"
    },
    "Tollian": {
        "noun": "Tollian",
        "verb": "Tollian"
    },
    "Shregami": {
        "noun": "Shregami",
        "verb": "Shrewgamic"
    },
}

titleStructure = {
    "default": {
        "ruler": {
            "male": "King",
            "female": "Queen",
        },
        "noble": {
            "male": "Lord",
            "female": "Lady",
        },
        "ovinatel": {
            "male": "Ovinatel",
            "female": "Ovinatel",
        },
        "religious": {
            "male": "Canon",
            "female": "Canon",
        },
        "military": {
            "male": "Sir",
            "female": "Lady",
        },
        "serf": {
            "male": "",
            "female": "",
        },
    }
}

nameStructure = {

}

cultures = {
    "Chorennian": {
        "titleStructure": titleStructure["default"],
        "nameStructure": "",
    },
    "Xaigonian": {},
    "Achaian": {},
    "Oxarean": {},
    "Qaidellian": {},
    "Mosian": {},
    "Gulberg": {},
    "Tollian": {},
    "Shrewgamic": {},
}

